#!/bin/bash

# 서버 배포 스크립트
# 사용법: ./server_deploy.sh

echo "=========================================="
echo "서버 배포 스크립트 시작"
echo "=========================================="

# SSH 접속 정보
SSH_HOST="webdev@220.69.240.143"
SSH_PORT="22001"
PROJECT_DIR="/home/webdev/to-do-ai"
GITHUB_REPO="https://github.com/Jeon-Hajun/To-do-ai"

echo ""
echo "1. SSH로 서버 접속 중..."
echo "   명령어: ssh $SSH_HOST -p $SSH_PORT"
echo "   비밀번호: webroqkfwk2025"
echo ""
echo "2. 서버 접속 후 다음 명령어들을 순서대로 실행하세요:"
echo ""
echo "=========================================="
echo "명령어 목록:"
echo "=========================================="
echo ""
echo "# 1. 프로젝트 디렉토리로 이동"
echo "cd $PROJECT_DIR"
echo ""
echo "# 2. 현재 상태 확인"
echo "git status"
echo ""
echo "# 3. GitHub에서 최신 코드 가져오기"
echo "git pull origin main"
echo ""
echo "# 4. 백엔드 디렉토리로 이동"
echo "cd backend"
echo ""
echo "# 5. 백엔드 프로세스 확인 (Node.js)"
echo "ps aux | grep node"
echo ""
echo "# 6. 백엔드 재시작 (PM2 사용 시)"
echo "# PM2를 사용하는 경우:"
echo "pm2 restart backend || pm2 start app.js --name backend"
echo ""
echo "# 또는 직접 실행하는 경우 기존 프로세스 종료 후:"
echo "# pkill -f 'node.*app.js'"
echo "# nohup node app.js > backend.log 2>&1 &"
echo ""
echo "# 7. AI 백엔드 프로세스 확인 (Flask)"
echo "ps aux | grep flask"
echo ""
echo "# 8. AI 백엔드 재시작"
echo "# 기존 프로세스 종료:"
echo "pkill -f 'python.*app.py' || pkill -f 'flask'"
echo ""
echo "# AI 백엔드 재시작:"
echo "cd $PROJECT_DIR/ai-backend"
echo "source venv/bin/activate"
echo "nohup python app.py > ai-backend.log 2>&1 &"
echo ""
echo "# 9. 프로세스 확인"
echo "ps aux | grep -E 'node|flask|python.*app.py'"
echo ""
echo "=========================================="
echo "완료!"
echo "=========================================="

